services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-root}
      - MYSQL_DATABASE=${DATABASE_NAME:-ecommerce}
    ports:
      - "${DATABASE_PORT:-3306}:3306"