spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:ecommerce}
    username: ${DATABASE_USERNAME:mysql}
    password: ${DATABASE_PASSWORD:root}
  application:
    name: ecommerce
  jpa:
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
    show-sql: ${JPA_SHOW_SQL:true}

logging:
  level:
      root: ${SPRING_LOG_LEVEL:WARN}
